select * from my_customer limit 50

---Q1. what is the total revenue generated by male vs female customers?

Select gender, SUM(purchase_amount) as revenue
from my_customer
group by gender

-- Q2. which customer used a discount but still spent more than the average purchase 

SELECT customer_id, purchase_amount 
from my_customer
where discount_applied='Yes' and purchase_amount>=(select avg(purchase_amount) from my_customer)

--Q3. which are the top 5 products with the highest average review rating?
SELECT item_purchased,ROUND( avg(review_rating::numeric),2) as "Average Product Rating"
from my_customer
group by item_purchased
order by avg(review_rating) desc
limit 5;


--Q4. compare the average purchase amount among standard and express shipping.
select shipping_type,
avg(purchase_amount)
from my_customer
where shipping_type in ('Standard','Express')
group by shipping_type

--Q5. do subscribed customers spend more? compare average spend and total revenue
--    between subscribed and non-subscribes

select subscription_status,
COUNT (customer_id) as total_customer,
ROUND(avg(purchase_amount),2) as avg_spend,
ROUND(sum(purchase_amount),2) as total_revenue
from my_customer
group by subscription_status
order by total_revenue, avg_spend desc;

--Q6 . which 5 products have the highest percentage with discount applied?

select item_purchased,
ROUND(100*sum(case when discount_applied='Yes' then 1 else 0 end)/count(*),2) as discount_rate
from my_customer
group by item_purchased
order by discount_rate desc
limit 5;

--Q7.Segment customer into new, returning and loyal based on their total
--   number of previous purchases, and show the count of each segment.

with customer_type as (
select customer_id, previous_purchases,
case
     when previous_purchases = 1 then 'New'
     when previous_purchases between 2 and 10 then 'Returning'
     else 'Loyal'
     END AS customer_segment
from my_customer

)
select customer_segment, count(*) as "Number of Customers"
from customer_type
group by customer_segment

--Q8. what are the top 3 most purchased products within each category..

with item_counts as (
select category,
item_purchased,
count(customer_id) as total_orders,
row_number() over (partition by category order by count(customer_id)desc) as item_rank
from my_customer
group by category, item_purchased
)
select item_rank, category, item_purchased, total_orders
from item_counts
where item_rank <=3

--Q9 .are customers are repeat buyers (more than 5 previous purchases) also likely to subscribe?

select subscription_status,
count(customer_id) as repeat_buyers
from my_customer
where previous_purchases > 5
group by subscription_status

--Q10 .what is the revenue contribution of each age group..

select age_group,
sum(purchase_amount) as total_revenue
from my_customer
group by age_group
order by total_revenue desc;





 


